In [7]:
import numpy as np
import pandas as pd
import torch

In [8]:
df = pd.read_csv('data/data.csv')

inputs = df.iloc[:,1:7].values
prices = df.iloc[:,-1:].values

print(inputs)
print(prices)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]
[[ 37.9]
 [ 42.2]
 [ 47.3]
 [ 54.8]
 [ 43.1]
 [ 32.1]
 [ 40.3]
 [ 46.7]
 [ 18.8]
 [ 22.1]
 [ 41.4]
 [ 58.1]
 [ 39.3]
 [ 23.8]
 [ 34.3]
 [ 50.5]
 [ 70.1]
 [ 37.4]
 [ 42.3]
 [ 47.7]
 [ 29.3]
 [ 51.6]
 [ 24.6]
 [ 47.9]
 [ 38.8]
 [ 27. ]
 [ 56.2]
 [ 33.6]
 [ 47. ]
 [ 57.1]
 [ 22.1]
 [ 25. ]
 [ 34.2]
 [ 49.3]
 [ 55.1]
 [ 27.3]
 [ 22.9]
 [ 25.3]
 [ 47.7]
 [ 46.2]
 [ 15.9]
 [ 18.2]
 [ 34.7]
 [ 34.1]
 [ 53.9]
 [ 38.3]
 [ 42. ]
 [ 61.5]
 [ 13.4]
 [ 13.2]
 [ 44.2]
 [ 20.7]
 [ 27. ]
 [ 38.9]
 [ 51.7]
 [ 13.7]
 [ 41.9]
 [ 53.5]
 [ 22.6]
 [ 42.4]
 [ 21.3]
 [ 63.2]
 [ 27.7]
 [ 55. ]
 [ 2

In [9]:
# convert numpy array to torch tensor
inputs = torch.from_numpy(inputs)
prices = torch.from_numpy(prices)
print(inputs)
print(prices)

tensor([[2012.9170,   32.0000,   84.8788,   10.0000,   24.9830,  121.5402],
        [2012.9170,   19.5000,  306.5947,    9.0000,   24.9803,  121.5395],
        [2013.5830,   13.3000,  561.9845,    5.0000,   24.9875,  121.5439],
        ...,
        [2013.2500,   18.8000,  390.9696,    7.0000,   24.9792,  121.5399],
        [2013.0000,    8.1000,  104.8101,    5.0000,   24.9667,  121.5407],
        [2013.5000,    6.5000,   90.4561,    9.0000,   24.9743,  121.5431]],
       dtype=torch.float64)
tensor([[ 37.9000],
        [ 42.2000],
        [ 47.3000],
        [ 54.8000],
        [ 43.1000],
        [ 32.1000],
        [ 40.3000],
        [ 46.7000],
        [ 18.8000],
        [ 22.1000],
        [ 41.4000],
        [ 58.1000],
        [ 39.3000],
        [ 23.8000],
        [ 34.3000],
        [ 50.5000],
        [ 70.1000],
        [ 37.4000],
        [ 42.3000],
        [ 47.7000],
        [ 29.3000],
        [ 51.6000],
        [ 24.6000],
        [ 47.9000],
        [ 38.8000],
  

In [10]:
# create weights and biases
# requires_grad=True enables us to leave computing the gradient of our loss
# function with respect to our weights and biases (backpropagation) to PyTorch.
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.5217,  0.3972, -1.6007],
        [ 0.9496, -1.2847,  0.3495]], requires_grad=True)
tensor([-1.3137,  0.1172], requires_grad=True)


In [31]:
class LinearRegression:
    def __init__(self, w, b):
        self.w = w
        self.b = b
    
    def predict(self, x):
        """Return the sum (element-wise) of bias and 
        the product of x with the transpose of weights.
        """
        return x.double() @ w.t().double() + b.double()
    
    def mse(self, t1, t2):
        """Return MSE loss."""
        d = t1 - t2
        return torch.sum(d * d) / d.numel()
    
    def train(self, epochs, inputs, prices, print_loss=False):
        """Train model."""
        for _ in range(epochs):
            predictions = self.predict(inputs)
            loss = self.mse(predictions, prices)
            if print_loss:
                print(loss)
            loss.backward()

            with torch.no_grad():
                self.w -= self.w.grad * 1e-5
                self.b -= self.b.grad * 1e-5

                # set gradients to zero
                self.w.grad.zero_()
                self.b.grad.zero_()

In [32]:
# create model and train for 1000 epochs
print(inputs.shape)
print(prices.shape)
w = torch.randn(inputs.shape[0], inputs.shape[1], requires_grad=True)
b = torch.randn(prices.shape[0], requires_grad=True)
model = LinearRegression(w, b)
model.train(1000, inputs, prices, True)

torch.Size([414, 6])
torch.Size([414, 1])
tensor(6999916.8285, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(4108532.8730, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2543777.9870, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1680756.9210, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1190713.3220, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(900496.8426, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(718740.7694, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(597080.6381, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(509779.1813, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(443019.8517, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(389279.3379, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(344368.2855, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(305873.8755, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(272339.0788, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(242829.1199, dtype=torch.float64, gr

tensor(238.7036, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.7011, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6987, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6964, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6941, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6919, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6897, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6876, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6855, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6834, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6814, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6794, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6774, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6755, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6736, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.6717, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2

tensor(238.3745, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3727, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3710, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3692, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3675, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3657, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3640, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3622, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3605, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3587, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3570, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3552, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3535, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3517, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3500, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.3482, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2

tensor(238.1384, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1367, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1349, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1332, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1315, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1297, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1280, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1262, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1245, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1227, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1210, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1192, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1175, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1157, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1140, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(238.1122, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2

tensor(237.8034, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.8016, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7999, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7981, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7964, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7946, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7929, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7912, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7894, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7877, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7859, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7842, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7824, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7807, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7790, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.7772, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2

tensor(237.4882, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4864, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4847, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4830, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4812, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4795, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4777, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4760, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4743, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4725, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4708, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4690, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4673, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4656, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4638, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(237.4621, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(2

In [33]:
# get loss
predictions = model.predict(inputs)
loss = model.mse(predictions, prices)
print(loss)
print(predictions)
print(prices)

tensor(1102889.5101, dtype=torch.float64)
tensor([[46.6461, 51.3724, 36.2147,  ..., 45.7009, 43.3601, 38.5928],
        [43.9104, 48.5919, 38.9465,  ..., 42.3442, 44.3237, 45.1837],
        [41.4245, 41.9331, 42.8215,  ..., 41.0269, 42.7457, 44.9252],
        ...,
        [43.1919, 45.5446, 40.5728,  ..., 42.4128, 43.2983, 43.6361],
        [44.2429, 44.2571, 48.2888,  ..., 43.7572, 47.0348, 51.2416],
        [44.3636, 49.4829, 44.5651,  ..., 41.9538, 48.6420, 55.5208]],
       dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[ 37.9000],
        [ 42.2000],
        [ 47.3000],
        [ 54.8000],
        [ 43.1000],
        [ 32.1000],
        [ 40.3000],
        [ 46.7000],
        [ 18.8000],
        [ 22.1000],
        [ 41.4000],
        [ 58.1000],
        [ 39.3000],
        [ 23.8000],
        [ 34.3000],
        [ 50.5000],
        [ 70.1000],
        [ 37.4000],
        [ 42.3000],
        [ 47.7000],
        [ 29.3000],
        [ 51.6000],
        [ 24.6000],
        [ 47